export const SET_USER = "SET_USER";

export const SET_BUDGET = "SET_BUDGET";

export const ADD_BUDGET = "ADD_BUDGET";
export const FETCHED_USER_BUDGETS = "FETCHED_USER_BUDGETS";

export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const FETCHED_ACCOUNTS = "FETCHED_ACCOUNTS";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const FETCHED_CATEGORIES = "FETCHED_CATEGORIES";

export const ADD_BUDGET_CATEGORY = "ADD_BUDGET_CATEGORY";
export const FETCHED_BUDGET_CATEGORIES = "FETCHED_BUDGET_CATEGORIES";
