export const SET_USER = "SET_USER";

export const ADD_BUDGET = "ADD_BUDGET";
export const FETCHED_USER_BUDGETS = "FETCHED_USER_BUDGETS";

export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const FETCHED_ACCOUNTS = "FETCHED_ACCOUNTS";
