export const SET_USER = "SET_USER";

export const SET_CURRENT_BUDGET = "SET_CURRENT_BUDGET";

export const SET_CURRENT_ACCOUNT = "SET_CURRENT_ACCOUNT";

export const ADD_BUDGET = "ADD_BUDGET";
export const FETCHED_USER_BUDGETS = "FETCHED_USER_BUDGETS";

export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const FETCHED_ACCOUNTS = "FETCHED_ACCOUNTS";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const FETCHED_CATEGORIES = "FETCHED_CATEGORIES";

export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const FETCHED_TRANSACTIONS = "FETCHED_TRANSACTIONS";
